//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class libro
{
    public int IdLibro { get; set; }
    public string Titulo { get; set; }
    public string Editorial { get; set; }
    public Nullable<int> AnioEdicion { get; set; }
    public Nullable<bool> Estado { get; set; }
    public Nullable<System.DateTime> FechaCreacion { get; set; }
}
